name: "Publish Image"

on:
  push:
    branches: ["main"]

jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout
      - uses: actions/setup-go
        with:
          go-version-file: go.mod
      - uses: ko-build/setup-ko
      - run: ko build
